spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yangchuantang
    url: jdbc:mysql://localhost:3306/sell2?serverTimezone=Asia/Shanghai
  application:
    name: store

server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mapper/*.xml


